steps:
# Build Links Website
- name: 'gcr.io/cloud-builders/docker'
  id: Build the links image
  args: [
    "build",
    "-t",
    "gcr.io/$PROJECT_ID/site-links",
    "links",
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: Push new Links image
  args: [
    "push",
    "gcr.io/$PROJECT_ID/site-links",
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Links to Cloud Run
  args: [
    "run",
    "deploy",
    "site-links",
    "--image",
    "gcr.io/$PROJECT_ID/site-links",
    "--region",
    "us-central1",
  ]

images:
  - "gcr.io/$PROJECT_ID/site-links"