steps:
# Build the links image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    "build",
    "-t",
    "gcr.io/$PROJECT_ID/site-links",
    "${_PATH}",
  ]
# Depoly to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    "run",
    "deploy",
    "site-links",
    "--image",
    "gcr.io/$PROJECT_ID/site-links",
    "--region",
    "us-central1",
  ]

substitutions:
  _PATH: .

images:
  - "gcr.io/$PROJECT_ID/site-links"