steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build the links image
  args: [
    "build",
    "-t",
    "gcr.io/$PROJECT_ID/site-links",
    "${_PATH}",
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: Push new image
  args: [
    "push",
    "gcr.io/$PROJECT_ID/site-links",
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy to Cloud run
  args: [
    "run",
    "deploy",
    "site-links",
    "--image",
    "gcr.io/$PROJECT_ID/site-links",
    "--region",
    "us-central1",
  ]

substitutions:
  _PATH: .

images:
  - "gcr.io/$PROJECT_ID/site-links"